import type { Menu } from "@/generated/prisma/client";

export const MENU_BAWAAN: Menu[] = [
  {
    id: "menu-1",
    nama: "Nasi Kotak Ayam Bakar",
    slug: "nasi-kotak-ayam-bakar",
    deskripsi:
      "Ayam bakar bumbu kecap yang dibakar dadakan, nasi putih pulen, tumis buncis, sambal, dan lalapan segar.",
    kategori: "NASI_KOTAK",
    harga: 28000,
    satuan: "kotak",
    minPesan: 10,
    fotoUrl: null,
    aktif: true,
    preorderHari: 0,
    kapasitasHarian: 150,
    urutan: 1,
    dibuatPada: new Date(),
    diubahPada: new Date(),
  },
  {
    id: "menu-2",
    nama: "Nasi Kotak Rendang Daging",
    slug: "nasi-kotak-rendang-daging",
    deskripsi:
      "Rendang daging masak semalaman sampai bumbunya meresap, dengan nasi putih, kentang balado, dan kerupuk.",
    kategori: "NASI_KOTAK",
    harga: 37000,
    satuan: "kotak",
    minPesan: 10,
    fotoUrl: null,
    aktif: true,
    preorderHari: 1,
    kapasitasHarian: 80,
    urutan: 2,
    dibuatPada: new Date(),
    diubahPada: new Date(),
  },
  {
    id: "menu-3",
    nama: "Nasi Kotak Ayam Goreng Lalapan",
    slug: "nasi-kotak-ayam-goreng-lalapan",
    deskripsi:
      "Ayam goreng kremes gurih, nasi putih hangat, tahu tempe, lalapan, dan sambal terasi buatan sendiri.",
    kategori: "NASI_KOTAK",
    harga: 25000,
    satuan: "kotak",
    minPesan: 10,
    fotoUrl: null,
    aktif: true,
    preorderHari: 0,
    kapasitasHarian: 150,
    urutan: 3,
    dibuatPada: new Date(),
    diubahPada: new Date(),
  },
  {
    id: "menu-4",
    nama: "Snack Box Rapat Kantor",
    slug: "snack-box-rapat-kantor",
    deskripsi:
      "Empat macam kue basah dan gorengan pilihan: risoles mayo, lemper ayam, kue lumpur, dan air mineral.",
    kategori: "SNACK",
    harga: 18000,
    satuan: "box",
    minPesan: 15,
    fotoUrl: null,
    aktif: true,
    preorderHari: 0,
    kapasitasHarian: 300,
    urutan: 1,
    dibuatPada: new Date(),
    diubahPada: new Date(),
  },
  {
    id: "menu-5",
    nama: "Paket Risoles Mayo (isi 10)",
    slug: "paket-risoles-mayo",
    deskripsi:
      "Risoles isi smoked beef, telur rebus, dan saus mayo creamy, digoreng renyah keemasan sebelum diantar.",
    kategori: "SNACK",
    harga: 38000,
    satuan: "paket",
    minPesan: 2,
    fotoUrl: null,
    aktif: true,
    preorderHari: 0,
    kapasitasHarian: 60,
    urutan: 2,
    dibuatPada: new Date(),
    diubahPada: new Date(),
  },
  {
    id: "menu-6",
    nama: "Tumpeng Kuning Komplit (15 Porsi)",
    slug: "tumpeng-kuning-komplit",
    deskripsi:
      "Tumpeng nasi kuning harum dengan ayam ungkep, sambal goreng ati kentang, urap sayur, perkedel, dan telur pindang.",
    kategori: "TUMPENG",
    harga: 575000,
    satuan: "paket",
    minPesan: 1,
    fotoUrl: null,
    aktif: true,
    preorderHari: 1,
    kapasitasHarian: 5,
    urutan: 1,
    dibuatPada: new Date(),
    diubahPada: new Date(),
  },
  {
    id: "menu-7",
    nama: "Nasi Goreng Spesial Telur Ceplok",
    slug: "nasi-goreng-spesial",
    deskripsi:
      "Nasi goreng bumbu racik dapur dengan suwiran ayam, bakso sapi, acar mentimun segar, kerupuk udang, dan telur mata sapi.",
    kategori: "NASI_GORENG",
    harga: 25000,
    satuan: "porsi",
    minPesan: 5,
    fotoUrl: null,
    aktif: true,
    preorderHari: 0,
    kapasitasHarian: 100,
    urutan: 1,
    dibuatPada: new Date(),
    diubahPada: new Date(),
  },
];

